---
- name: Activate the overlay for 1-wire
  ansible.builtin.lineinfile:
    path: /boot/firmware/config.txt
    line: dtoverlay=w1-gpio,gpiopin=4
    regexp: '^dtoverlay=w1.*$'
  become: true
  notify: Reboot the server
