---
- name: Activate the overlay for 1-wire
  lineinfile:
    path: /boot/config.txt
    line: dtoverlay=w1-gpio,gpiopin=4
    regexp: '^dtoverlay=w1.*$'
  become: true
  notify: Reboot temperature
- name: Add an Apt signing key, uses whichever key is at the URL
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present
  become: true
- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
  become: true
- name: Create a directory for the temperature exporter
  file:
    state: directory
    path: /home/pi/temperature
- name: Create the Python script
  copy:
    src: ../sensor/temperature.py
    dest: /home/pi/temperature/temperature.py
    mode: '0755'
- name: Create the systemd service file
  copy:
    src: ../sensor/temperature.service
    dest: /home/pi/temperature/temperature.service
    mode: '0644'
- name: Create a symlink to activate the service file
  file:
    state: link
    src: /home/pi/temperature/temperature.service
    dest: /etc/systemd/system/temperature.service
  become: true
- name: Make sure the temperature service is running
  ansible.builtin.systemd:
    state: started
    enabled: yes
    name: temperature
  become: true
- name: Install Prometheus
  package:
    name:
      - prometheus
  become: true
- name: Remove prometheus-node-exporter
  ansible.builtin.package:
    name: prometheus-node-exporter
    state: absent
  become: true
- name: Configure Prometheus to use temperature data only
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Restart Prometheus
- name: Make sure prometheus is running
  ansible.builtin.systemd:
    state: started
    enabled: yes
    name: prometheus
  become: true
- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
  become: true
- name: Install Grafana
  package:
    name:
      - grafana
  become: true
- name: Make sure grafana is running
  ansible.builtin.systemd:
    state: started
    enabled: yes
    name: grafana-server
  become: true

