---
- name: Activate the overlay for 1-wire
  ansible.builtin.lineinfile:
    path: /boot/firmware/config.txt
    line: dtoverlay=w1-gpio,gpiopin=4
    regexp: '^dtoverlay=w1.*$'
  become: true
  notify: Reboot the server
- name: Remove one browser
  ansible.builtin.package:
    name: firefox
    state: absent
  become: true
- name: Set language
  ansible.builtin.command:
    cmd: "/usr/bin/raspi-config nonint do_change_locale {{ config_lang }}"
  become: true
- name: Set keymap
  ansible.builtin.command:
    cmd: "/usr/bin/raspi-config nonint do_configure_keyboard {{ config_keymap }}"
  become: true
