---
- name: Copy uncompressed image into a new image file
  ansible.builtin.copy:
    src: "{{ image_plain_pathname }}"
    dest: "{{ image_file }}"
    mode: "0644"
- name: Get partition data of the image
  ansible.builtin.command:
    cmd: "sfdisk -J {{ image_file }}"
  register: partitions
  changed_when: false
- name: Create the mount point
  ansible.builtin.file:
    state: directory
    path: "{{ mount_dir_boot }}"
    mode: "0755"
- name: Select boot partition
  ansible.builtin.set_fact:
    partition_boot: "{{ (partitions.stdout | from_json).partitiontable.partitions[0] }}"
- name: Print boot partition
  ansible.builtin.debug:
    msg: "Boot Partition Start: {{ partition_boot }}"
- name: Print boot partition start and size in bytes
  ansible.builtin.debug:
    msg: "Start: {{ partition_boot.start * 512 }}, Size: {{ partition_boot.size * 512 }}"
- name: Mount boot partition
  ansible.posix.mount:
    src: "{{ image_file }}"
    path: "{{ mount_dir_boot }}"
    opts: "loop,offset={{ partition_boot.start * 512 }},sizelimit={{ partition_boot.size * 512 }},umask=000"
    fstype: vfat
    state: ephemeral
  become: true
