---
- name: Create the archive directory
  ansible.builtin.file:
    state: directory
    path: "{{ archive_dir }}"
    mode: "0755"
- name: Download the compressed OS image file
  ansible.builtin.get_url:
    url: "{{ archive_url }}"
    dest: "{{ archive_file }}"
    mode: '0440'
    force: false
    checksum: "{{ archive_checksum }}"
- name: Create the temporary directory
  ansible.builtin.file:
    state: directory
    path: "{{ temp_dir }}"
    mode: "0755"
- name: Uncompress the compressed OS image file
  ansible.builtin.shell:
    cmd: "xz --keep --stdout --decompress {{ archive_file }} > {{ image_file }}"
    creates: "{{ image_file }}"
