---
- name: Check current LANG (avoid unnecessary config change)
  ansible.builtin.set_fact:
    current_locale: "{{ ansible_facts.env.LANG }}"
- name: Set language
  ansible.builtin.command:
    cmd: "/usr/bin/raspi-config nonint do_change_locale {{ temp.lang }}"
  when: current_locale != temp.lang
  changed_when: current_locale != temp.lang
  become: true
- name: Check current keymap in Wayland
  ansible.builtin.lineinfile:
    path: "/home/{{ ansible_user }}/.config/wayfire.ini"
    regexp: "^xkb_layout\\s*=\\s*{{ temp.keyboard.layout }}"
    state: absent
  check_mode: true
  changed_when: false
  register: missing
- name: Set keymap
  ansible.builtin.command:
    cmd: "/usr/bin/raspi-config nonint do_configure_keyboard {{ temp.keyboard.layout }}"
  when: not missing.found
  changed_when: not missing.found
  become: true
