---
- name: Umount boot partition
  ansible.posix.mount:
    path: "{{ mount_dir_boot }}"
    state: unmounted
  become: true
- name: Umount root partition
  ansible.posix.mount:
    path: "{{ mount_dir_root }}"
    state: unmounted
  become: true
