---
- name: Create a directory for the temperature exporter
  ansible.builtin.file:
    state: directory
    path: /home/pi/temperature
    mode: "0755"
- name: Create the Python script
  ansible.builtin.copy:
    src: ../sensor/temperature.py
    dest: /home/pi/temperature/temperature.py
    mode: '0755'
  notify: Restart temperature service
- name: Copy the test directory
  ansible.builtin.copy:
    src: ../sensor/test
    dest: /home/pi/temperature
    mode: '0755'
  notify: Restart temperature service
- name: Create the systemd service file
  ansible.builtin.copy:
    src: ../sensor/temperature.service
    dest: /home/pi/temperature/temperature.service
    mode: '0644'
  notify: Restart temperature service
- name: Create a symlink to activate the service file
  ansible.builtin.file:
    state: link
    src: /home/pi/temperature/temperature.service
    dest: /etc/systemd/system/temperature.service
  become: true
- name: Make sure the temperature service is running
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: temperature
  become: true
