---
- name: Install git
  ansible.builtin.package:
    name:
      - git
- name: Use SSH private key to access git
  community.general.ssh_config:
    user: git
    host: github.com
    identity_file: '{{ ssh_keyfile_private }}'
- name: Clone git repo
  ansible.builtin.git:
    repo: git@github.com:girlich/temperature.git
    dest: '{{ git_dir }}'
    version: main
- name: Configure git to remove the pull warning
  community.general.git_config:
    repo: '{{ git_dir }}'
    scope: local
    name: pull.rebase
    value: "false"
- name: Set commit user name
  community.general.git_config:
    repo: '{{ git_dir }}'
    scope: local
    name: user.name
    value: 'Uwe Girlich on {{ host_name }}'
- name: Set commit user email address
  community.general.git_config:
    repo: '{{ git_dir }}'
    scope: local
    name: user.email
    value: uwe.girlich@gmail.com

