---
- name: Install git
  ansible.builtin.package:
    name:
      - git
- name: Install stormssh
  ansible.builtin.pip:
    name:
      - stormssh
- name: Copy the private SSH key to be used as github deploy key
  ansible.builtin.copy:
    src: '{{ ssh_keyfile_private }}'
    dest: ~/.ssh/id_rsa_github
    mode: "0600"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
- name: Use SSH private key to access git
  community.general.ssh_config:
    user: '{{ ansible_user }}'
    remote_user: git
    host: github.com
    identity_file: ~/.ssh/id_rsa_github
- name: Clone git repo
  ansible.builtin.git:
    repo: git@github.com:girlich/temperature.git
    dest: '{{ git_dir }}'
    version: main
- name: Configure git to remove the pull warning
  community.general.git_config:
    repo: '{{ git_dir }}'
    scope: local
    name: pull.rebase
    value: "false"
- name: Set commit user name
  community.general.git_config:
    repo: '{{ git_dir }}'
    scope: local
    name: user.name
    value: '{{ git_user_name }} on {{ host_name }}'
- name: Set commit user email address
  community.general.git_config:
    repo: '{{ git_dir }}'
    scope: local
    name: user.email
    value: '{{ git_user_email }}'
