---
- name: Install some basic packages
  ansible.builtin.package:
    name:
      - git
      - python3-paramiko
  become: true
- name: Get stats of python3
  ansible.builtin.stat:
    path: /usr/bin/python3
  register: st
- name: Remove EXTERNALLY-MANAGED
  ansible.builtin.file:
    path: "/usr/lib/{{ st.stat.lnk_target }}/EXTERNALLY-MANAGED"
    state: absent
  become: true
- name: Install stormssh via pip
  ansible.builtin.pip:
    name:
      - stormssh
- name: Copy the private SSH key to be used as github deploy key
  ansible.builtin.copy:
    src: '{{ ssh_keyfile_private }}'
    dest: ~/.ssh/id_rsa_github
    mode: "0600"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
- name: Use SSH private key to access git
  community.general.ssh_config:
    user: '{{ ansible_user }}'
    remote_user: git
    host: github.com
    identity_file: ~/.ssh/id_rsa_github
- name: Prepare a ready made list of known hosts (downloaded from https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/githubs-ssh-key-fingerprints)
  ansible.builtin.copy:
    src: known_hosts
    dest: ~/.ssh/known_hosts
    mode: "0600"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
- name: Clone git repo
  ansible.builtin.git:
    repo: git@github.com:girlich/temperature.git
    dest: '{{ git_dir }}'
    version: main
- name: Configure git to remove the pull warning
  community.general.git_config:
    repo: '{{ git_dir }}'
    scope: local
    name: pull.rebase
    value: "false"
- name: Set commit user name
  community.general.git_config:
    repo: '{{ git_dir }}'
    scope: local
    name: user.name
    value: '{{ git_user_name }} on {{ host_name }}'
- name: Set commit user email address
  community.general.git_config:
    repo: '{{ git_dir }}'
    scope: local
    name: user.email
    value: '{{ git_user_email }}'
