---
- name: Install Prometheus
  ansible.builtin.package:
    name:
      - prometheus
  become: true
- name: Remove prometheus-node-exporter
  ansible.builtin.package:
    name: prometheus-node-exporter
    state: absent
  become: true
- name: Configure Prometheus command line options
  ansible.builtin.template:
    src: prometheus.j2
    dest: /etc/default/prometheus
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Restart Prometheus
- name: Configure Prometheus to use temperature data only
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Restart Prometheus
- name: Make sure prometheus is running
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: prometheus
  become: true
