---
- name: Prepare the SD card of the Raspberry Pi temperature sensor server
  hosts: localhost
  connection: local
  gather_facts: true
  roles:
    - image_download
    - ssh_keys
    - boot_mount
    - boot_prepare
    - boot_umount
    - sd_write
