---
- name: Get the information about the device
  ansible.builtin.shell: |
    set -o pipefail
    ls -l /dev/disk/by-id|grep "\\.\\./\\.\\./{{ temp.sd.device }}"
  register: result
  changed_when: false
- name: Wait for confirmation to overwrite the device
  ansible.builtin.pause:
    prompt: "{{ result }}"
- name: Write image to the sd card
  ansible.builtin.command: # noqa: no-changed-when
    cmd: "dd if={{ image_file }} of={{ sd_device }} bs=10M status=progress"
  become: true
- name: Flush all buffers
  ansible.builtin.command: # noqa: no-changed-when
    cmd: "sync"
