---
- name: Get the information about the device
  shell:
    cmd: "ls -l /dev/disk/by-id|grep \\.\\./\\.\\./{{ sd_name }}"
  register: result
- name: Write the device name and wait for confirmation
  pause:
    prompt: "{{ result }}"
- name: Write image to the sd card
  command:
    cmd: "dd if={{ image_file }} of={{ sd_device }} bs=10M"
  become: true
- name: Flush all buffers
  command:
    cmd: "sync"
